[tool.poetry]
name = "storytime"
version = "0.1.0"
description = "A terminal (TUI) app to view interactive stories"
authors = ["Dronakurl <konrad2710@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
textual = {extras = ["dev"], version = "^0.22.3"}

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
pre-commit = "^3.2.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120

[tool.pyright]
include = ["**/*.py"]
exclude = [ "**/__pycache__",
    "Archiv/**"
    , "data/**"
]
ignore = ["**/__init__.py"]
typeCheckingMode = "off"
reportGeneralTypeIssues = false
reportMissingTypeStubs = false
useLibraryCodeForTypes = false
pythonVersion = "3.11"
pythonPlatform = "Linux"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = [
    "--import-mode=importlib",
    "-ra -q",
    "--disable-warnings",
    "--ignore=Archiv",
]
pythonpath = ["."]
# testpaths = [
#     "spider/test",
#     "imgclass/test",
#     "utils/test",
# ]
